const products = [
  {
    '_id': '1',
    'name':'ladybug',
    'image': '/images/ladybug.jpeg',
    'description': 'small and usually quite round in shape. The color on the wing covers (elytra) can be yellow, orange, or red and often has small black dots on it. Some species are solid black.',
    'family': 'beetles',
    'size': 3,
    'life-expectancy': 24,
    'flight-capability': 'Yes',
    'price': 100.00,
    'rating': 4.5,
    'numReviews': 267,
  },

  {
    '_id': '2',
    'name':'driver ant',
    'image': '/images/driverant.jpeg',
    'description': 'characterized by a nomadic existence alternating with quiet, egg-laying periods.',
    'family': 'ants',
    'size':2,
    'life-expectancy':40,
    'flight-capability': 'No',
    'price': 40.00,
    'rating': 5,
    'numReviews': 17,
  },

  {
    '_id': '3',
    'name':'bumblebee',
    'image': '/images/bumblebee.jpeg',
    'description': 'a widely distributed social insect know for its ability to collect nectar from flowers and pollinate plants. Bumblebees are large yellow and black flying insects with a distinct buzz. There is variation in coloration among bumblebees and some species have bands of red, yellow and black.',
    'family': 'bees',
    'size':3,
    'life-expectancy': 34,
    'flight-capability': 'Yes',
    'price': 70.00,
    'rating': 4.0,
    'numReviews': 21,
  },

  {
    '_id': '4',
    'name':'braconid',
    'image': '/images/braconid.jpeg',
    'description': '',
    'family': 'wasps',
    'size':'',
    'life-expectancy':'',
    'flight-capability': 'Yes',
    'price': 10.00,
    'rating': 4.5,
    'numReviews': 2,

  },

  {
    '_id': '5',
    'name':'blister beetle',
    'image': '/images/blisterbeetle.jpeg',
    'description': '',
    'family': 'beetle',
    'size':'',
    'life-expectancy':'',
    'flight-capability': 'Yes',
    'price': 100.00,
    'rating': 4.5,
    'numReviews': 2,
  },

  {
    '_id': '6',
    'name':'billbug',
    'image': '/images/billbug.jpeg',
    'description': '',
    'family': 'weevils',
    'size':'',
    'life-expectancy':'',
    'flight-capability': 'Yes',
    'price': 100.00,
    'rating': 4.5,
    'numReviews': 2,
  },
  {
    '_id': '7',
    'name':'admiral',
    'image': '/images/admiral.jpeg',
    'description': '',
    'family': 'butterflies',
    'size':'',
    'life-expectancy':'',
    'flight-capability': 'Yes',
    'price': 100.00,
    'rating': 4.5,
    'numReviews': 2,
  },

  {
    '_id': '8',
    'name':'carpenter moth',
    'image': '/images/carpenter moth.jpeg',
    'description': '',
    'family': 'moths',
    'size':'',
    'life-expectancy':'',
    'flight-capability': 'Yes',
    'price': 100.00,
    'rating': 4.5,
    'numReviews': 2,
  },

  {
    '_id': '9',
    'name':'cone-headed grasshopper',
    'image': '/images/coneheadedgrasshopper.jpeg',
    'description': '',
    'family': 'grasshoppers',
    'size':'',
    'life-expectancy':'',
    'flight-capability': 'Yes',
    'price': 100.00,
    'rating': 4.5,
    'numReviews': 2,
  },
]

export default products;